require("soso.plugins-setup")
require("soso.core.options")
require("soso.core.keymaps")
require("soso.core.colorscheme")
require("soso.plugins.comment")
require("soso.plugins.nvim-tree")
require("soso.plugins.lualine")
require("soso.plugins.telescope")
require("soso.plugins.nvim-cmp")
-- require("soso.plugins.lsp.mason")
require("soso.plugins.lsp.lspconfig")
require("soso.plugins.lsp.null-ls")
require("soso.plugins.autopairs")
-- require("soso.plugins.treesitter")
require("soso.plugins.gitsigns")
